name: Deploy to Production

on:
  pull_request:
    branches:
    - production

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deployment
      env:
        DEPLOY_STAGE: production
        DEPLOY_KEY: ${{ secrets.PRODUCTION_DEPLOY_KEY }}
      run: |
        script/deploy
