name: Deploy to Staging

on:
  pull_request:
    branches:
    - master

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deployment
      env:
        DEPLOY_STAGE: staging
        DEPLOY_KEY: "{{ github.secrets.STAGING_DEPLOY_KEY }}"
      run: |
        script/deploy
